### ISSUE TITLE
Manage Settings button crashes APP.

### ISSUE THREAD

**Issue by teejayhh** [osano/cocoapods-specs#11]
Hello, I am following your documentation  as good as I can but I am running into an issue that `Manage Settings` Button on the consent dialog leads to an app crash

```
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x10aa0b810>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'
```

I am calling the documented code in the `viewDidLoad` of my controller where I want to show the consent dialog. Is there anything else, which needs to be done here? I also want to point out that the ConsentManager instance `needs` to be instantiated as early as possible during the appstart process (AppDelegate for instance) If you leave this to the until when you create the UIBuilder the consent manager probably wont have collected the user data and the dialog is not functional / broken. This should be clearly stated in your documentation. 

I hope that someone could look into this. 
Cheers Thomas

**Comment by ethanfann** [comment]
It's regrettable that Osano wasn't able to fit your needs. For those who come across this in the future, the problem most likely stems from the way our preferences drawer was being attached to a view. Our documentation will be updated to make this part of implementation clearer.
