### ISSUE TITLE
SPM fails checksum

### ISSUE THREAD

**Issue by hsingh-texada** [osano/cocoapods-specs#2]
I am following the [documentation](https://developers.osano.com/cmp/ios-sdk/installation/swift-package-manager) to integrate with the ConsentSDK using SPM on iOS. When tryiing to use the package as specified in the documentation, Xcode throws the following error:

`checksum of downloaded artifact of binary target 'ConsentSDK' (653fbf3e7c7363c1a23a1c2159be0834f9bfe4ace8c720ff05d17c913e2e7cf3) does not match checksum specified by the manifest (8361442a998fd4376b3b7ea026631b6d3a71383a83ac6c87b6038b950cb68923)`

Can you plese look into the issue resolve it. 

I am using Xcode 15.0

**Comment by ethanfann** [comment]
Whoops, merging that auto closed this. Updated our SPM definition to point to our most recent version, 3.1.0. Let us know if you are still encountering checksum issues.

**Comment by hsingh-texada** [comment]
It still doesn't work. I guess the reason is because you didn't tag the new release. 

Also just FYI, developers who try to pull in `3.0.0` will always see the checksum error. So, either you should fix `3.0.0` or remove `3.0.0` (because it will always fail) and suggest consumers to use `3.1.0` and above.

**Comment by ethanfann** [comment]
Thank you for your patience as we worked on this issue. Version 3.1.0 has now been tagged and should be the default suggestion in Swift Package Manager. This version finalizes support for IAB TCF 2.2, and we highly recommend it for implementation. I'll look into the possibility of removing version 3.0.0 from suggestions

**Comment by hsingh-texada** [comment]
The issue is resolved. Thanks.
