### ISSUE TITLE
Wrong country code

### ISSUE THREAD

**Issue by skyfoxa** [osano/cocoapods-specs#4]
I'm working on SDK integration, and it seems I can't test the consent alert for any country other than the US. Since I'm based in Prague, I assume it should work without any additional setup. I even tried to use VPN but the alert still looks the same, like the alert for US.

Can you help me understand how to correctly set or update the country code so that it functions as expected?

I'm on SDK version 3.1.0

![image](https://github.com/osano/cocoapods-specs/assets/20537160/14a50437-752f-4295-90d9-bac681a209e4)
![image](https://github.com/osano/cocoapods-specs/assets/20537160/23c90fbd-0c2a-4318-8210-8dc1c9ac0760)

**Comment by ethanfann** [comment]
Hello @skyfoxa, Osano SDK dev here. We noticed this issue and recently published version 3.1.1 which should correctly use geolocation headers served by the consent config network request. Let me know if you're still encountering the bug after updating.
