### ISSUE TITLE
Enable `UIModalPresentationStyle` for dialog view controller

### ISSUE THREAD

**Issue by skyfoxa** [osano/cocoapods-specs#6]
When `showDialogViewController` is called, it takes the `ConsentUiBuilder.PresentationType` argument. We have a use case where we want to customize the presentation style to avoid scaling down the parent presenter when using full screen or bottom sheet options. Is it possible to enable setting the `UIModalPresentationStyle` variable for the dialog view controller either on initialization or through a variable?

https://github.com/osano/cocoapods-specs/assets/20537160/ead1e2f2-75d3-44f7-996b-93cc9a929fb0

**Comment by ethanfann** [comment]
Hello again @skyfoxa. I believe my comment in #5 will be of use here. It shows how we can extract a view controller from `consentUiBuilder.categoriesViewController` which allows you to modify the presentation style as needed.
